### ISSUE TITLE
./synclibs.sh

### ISSUE THREAD

**Issue by MaxFuwin** [siren186/libbde4fool#1]
为什么我每一次输入./synclibs.sh的时候都会显示“Fatal Error”？
我一开始以为是防火墙的问题，所以我就开了VPN，结果开了VPN都没有用

**Comment by siren186** [comment]
这个仓库里面已经全打包好了，不用执行这些脚本。直接用visual studio打开sln工程就能编译了

**Comment by MaxFuwin** [comment]
我用的是autoconf编译的，但是我还是没办法#include，这是怎么回事？
